"""
SoomaaliPy - Tokens and Language Mappings.
Waxay qeexaysaa erayada furaha ah ee Af-Soomaaliga iyo u dhigmahooda Python.
"""

from typing import Dict, Set

# Mappings from Somali keywords to Python keywords
# Erayada furaha ah (Keywords)
SOMALI_TO_PYTHON_KEYWORDS: Dict[str, str] = {
    # Xaalado & Go'aanno (Conditions & Control flow)
    "haddii": "if",
    "haddii_kale": "elif",
    "kale_haddii": "elif",
    "kale": "else",
    
    # Wareegyo (Loops)
    "inta": "while",
    "kasta": "for",
    "ee": "for",
    "ku": "in",
    "ku_jira": "in",
    "jooji": "break",
    "jebi": "break",
    "sii_wad": "continue",
    "dhaaf": "pass",
    "gudbi": "pass",
    
    # Hawlo & Fasallo (Functions & Classes)
    "hawl": "def",
    "shaqo": "def",
    "celi": "return",
    "soo_celi": "return",
    "dhal": "yield",
    "fasal": "class",
    "hawl_gaaban": "lambda",
    "lambda": "lambda",
    
    # Khaladaad & Hubin (Exceptions & Handling)
    "isku_day": "try",
    "qabo": "except",
    "ugu_dambeyn": "finally",
    "dambeyn": "finally",
    "tuur": "raise",
    "kici": "raise",
    "xaqiiji": "assert",
    
    # Qiimayaal & Macquul (Booleans & Logic)
    "Run": "True",
    "run": "True",
    "Been": "False",
    "been": "False",
    "Waxba": "None",
    "waxba": "None",
    "Eber": "None",
    "eber": "None",
    "iyo": "and",
    "ama": "or",
    "ma": "not",
    "ma_aha": "not",
    "waa": "is",
    
    # Soo dajin & Xirmooyin (Modules & Scope)
    "soo_daji": "import",
    "ka": "from",
    "sida": "as",
    "la": "with",
    "caalami": "global",
    "gudaha_kale": "nonlocal",
    "tirtir": "del",
    "isku_mar": "async",
    "sug": "await",
}

# Python keywords to canonical Somali equivalents (for reverse transpiling)
PYTHON_TO_SOMALI_KEYWORDS: Dict[str, str] = {
    "if": "haddii",
    "elif": "haddii_kale",
    "else": "kale",
    "while": "inta",
    "for": "kasta",
    "in": "ku",
    "break": "jooji",
    "continue": "sii_wad",
    "pass": "dhaaf",
    "def": "hawl",
    "return": "celi",
    "yield": "dhal",
    "class": "fasal",
    "lambda": "hawl_gaaban",
    "try": "isku_day",
    "except": "qabo",
    "finally": "ugu_dambeyn",
    "raise": "tuur",
    "assert": "xaqiiji",
    "True": "Run",
    "False": "Been",
    "None": "Waxba",
    "and": "iyo",
    "or": "ama",
    "not": "ma",
    "is": "waa",
    "import": "soo_daji",
    "from": "ka",
    "as": "sida",
    "with": "la",
    "global": "caalami",
    "nonlocal": "gudaha_kale",
    "del": "tirtir",
    "async": "isku_mar",
    "await": "sug",
}

# Hawlaha Diyaar-ka-ah (Built-in Functions)
SOMALI_TO_PYTHON_BUILTINS: Dict[str, str] = {
    "daabac": "print",
    "geli": "input",
    "aqri": "input",
    "dherer": "len",
    "tirsan": "range",
    "tirooyinka": "range",
    "isku_dar": "sum",
    "ugu_yar": "min",
    "ugu_weyn": "max",
    "tiro": "int",
    "tiro_idil": "int",
    "jajab": "float",
    "qoraal": "str",
    "xaqiijin": "bool",
    "liis": "list",
    "qaamuus": "dict",
    "urur": "set",
    "lamaane": "tuple",
    "nooc": "type",
    "fur": "open",
    "dhab": "abs",
    "wareeg": "round",
    "kala_sooc": "sorted",
    "rog": "reversed",
    "dhammaan": "all",
    "wax_uun": "any",
    "tiri": "enumerate",
    "isku_xidh": "zip",
    "khariidad": "map",
    "shaandhee": "filter",
    "caawin": "help",
    "ka_bax": "exit",
    "bax": "quit",
    "ma_noocaa": "isinstance",
    "ma_farac_ba": "issubclass",
    "aqoonsi": "id",
    "furre": "hash",
    "tusmo": "dir",
    "awood": "pow",
    "xaraf": "chr",
    "xaraf_tiro": "ord",
}

PYTHON_TO_SOMALI_BUILTINS: Dict[str, str] = {
    "print": "daabac",
    "input": "geli",
    "len": "dherer",
    "range": "tirsan",
    "sum": "isku_dar",
    "min": "ugu_yar",
    "max": "ugu_weyn",
    "int": "tiro",
    "float": "jajab",
    "str": "qoraal",
    "bool": "xaqiijin",
    "list": "liis",
    "dict": "qaamuus",
    "set": "urur",
    "tuple": "lamaane",
    "type": "nooc",
    "open": "fur",
    "abs": "dhab",
    "round": "wareeg",
    "sorted": "kala_sooc",
    "reversed": "rog",
    "all": "dhammaan",
    "any": "wax_uun",
    "enumerate": "tiri",
    "zip": "isku_xidh",
    "map": "khariidad",
    "filter": "shaandhee",
    "help": "caawin",
    "exit": "ka_bax",
    "quit": "bax",
    "isinstance": "ma_noocaa",
    "issubclass": "ma_farac_ba",
    "id": "aqoonsi",
    "hash": "furre",
    "dir": "tusmo",
    "pow": "awood",
    "chr": "xaraf",
    "ord": "xaraf_tiro",
}

# Magacyada Khaladaadka (Exception Names)
SOMALI_TO_PYTHON_EXCEPTIONS: Dict[str, str] = {
    "Khalad": "Exception",
    "KhaladAsal": "BaseException",
    "KhaladNaxwo": "SyntaxError",
    "KhaladQoraal": "SyntaxError",
    "KhaladMagac": "NameError",
    "KhaladNooc": "TypeError",
    "KhaladQiimo": "ValueError",
    "KhaladTusmo": "IndexError",
    "KhaladFure": "KeyError",
    "KhaladEberLooQaybiyay": "ZeroDivisionError",
    "FaylLaWaayey": "FileNotFoundError",
    "KhaladSooDajin": "ImportError",
    "QaybLaWaayey": "ModuleNotFoundError",
    "KhaladSifo": "AttributeError",
    "JoojiKuCeliska": "StopIteration",
    "JoojinGacmeed": "KeyboardInterrupt",
    "KhaladKordhac": "RuntimeError",
    "KhaladKuCelcelis": "RecursionError",
    "KhaladXaqiijin": "AssertionError",
}

PYTHON_TO_SOMALI_EXCEPTIONS: Dict[str, str] = {
    "Exception": "Khalad",
    "BaseException": "KhaladAsal",
    "SyntaxError": "KhaladNaxwo",
    "NameError": "KhaladMagac",
    "TypeError": "KhaladNooc",
    "ValueError": "KhaladQiimo",
    "IndexError": "KhaladTusmo",
    "KeyError": "KhaladFure",
    "ZeroDivisionError": "KhaladEberLooQaybiyay",
    "FileNotFoundError": "FaylLaWaayey",
    "ImportError": "KhaladSooDajin",
    "ModuleNotFoundError": "QaybLaWaayey",
    "AttributeError": "KhaladSifo",
    "StopIteration": "JoojiKuCeliska",
    "KeyboardInterrupt": "JoojinGacmeed",
    "RuntimeError": "KhaladKordhac",
    "RecursionError": "KhaladKuCelcelis",
    "AssertionError": "KhaladXaqiijin",
}

# Complete mapping for token translation (Somali -> Python)
ALL_SOMALI_TO_PYTHON: Dict[str, str] = {
    **SOMALI_TO_PYTHON_KEYWORDS,
    **SOMALI_TO_PYTHON_BUILTINS,
    **SOMALI_TO_PYTHON_EXCEPTIONS,
}

# Complete mapping for reverse translation (Python -> Somali)
ALL_PYTHON_TO_SOMALI: Dict[str, str] = {
    **PYTHON_TO_SOMALI_KEYWORDS,
    **PYTHON_TO_SOMALI_BUILTINS,
    **PYTHON_TO_SOMALI_EXCEPTIONS,
}
